
-- -----------------------------------------------------
-- insert numbers_small
-- -----------------------------------------------------
INSERT INTO numbers_small VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);


-- -----------------------------------------------------
-- insert numbers
-- -----------------------------------------------------
INSERT INTO numbers
 SELECT thousands.number * 1000 + hundreds.number * 100 + tens.number * 10 + ones.number
 FROM numbers_small thousands, numbers_small hundreds, numbers_small tens, numbers_small ones
 LIMIT 1000000;


-- -----------------------------------------------------
-- insert dates_dimension
-- -----------------------------------------------------
INSERT INTO dates_dimension (date_id, date)
 SELECT number, DATE_ADD( '2014-01-01', INTERVAL number DAY )
 FROM numbers
 WHERE DATE_ADD( '2014-01-01', INTERVAL number DAY ) BETWEEN '2014-01-01' AND '2024-12-31'
 ORDER BY number;


-- -----------------------------------------------------
-- update dates_dimension
-- -----------------------------------------------------
UPDATE dates_dimension SET
 day             = DATE_FORMAT( date, "%W" ),
 day_of_week     = DAYOFWEEK(date),
 week_day        = WEEKDAY(date),
 day_of_month    = DATE_FORMAT( date, "%d" ),
 day_of_year     = DATE_FORMAT( date, "%j" ),
 previous_day    = DATE_ADD(date, INTERVAL -1 DAY),
 next_day        = DATE_ADD(date, INTERVAL 1 DAY),
 weekend         = IF( DATE_FORMAT( date, "%W" ) IN ('Saturday','Sunday'), 'Weekend', 'Weekday'),
 week_of_year    = DATE_FORMAT( date, "%v" ),
 week_year       = DATE_FORMAT( date, "%x" ),
 month           = DATE_FORMAT( date, "%M"),
 month_of_year   = DATE_FORMAT( date, "%m"),
 quarter_of_year = QUARTER(date),
 year            = DATE_FORMAT( date, "%Y" );


-- -----------------------------------------------------
-- insert times_dimension
-- -----------------------------------------------------
INSERT INTO times_dimension (time_id, time, hour) VALUES
 ('0', '00:00:00', '00'),
 ('1', '01:00:00', '01'),
 ('2', '02:00:00', '02'),
 ('3', '03:00:00', '03'),
 ('4', '04:00:00', '04'),
 ('5', '05:00:00', '05'),
 ('6', '06:00:00', '06'),
 ('7', '07:00:00', '07'),
 ('8', '08:00:00', '08'),
 ('9', '09:00:00', '09'),
 ('10', '10:00:00', '10'),
 ('11', '11:00:00', '11'),
 ('12', '12:00:00', '12'),
 ('13', '13:00:00', '13'),
 ('14', '14:00:00', '14'),
 ('15', '15:00:00', '15'),
 ('16', '16:00:00', '16'),
 ('17', '17:00:00', '17'),
 ('18', '18:00:00', '18'),
 ('19', '19:00:00', '19'),
 ('20', '20:00:00', '20'),
 ('21', '21:00:00', '21'),
 ('22', '22:00:00', '22'),
 ('23', '23:00:00', '23');


-- -----------------------------------------------------
-- insert category
-- -----------------------------------------------------
INSERT INTO category (categoryid, categoryname) VALUES
 (1, 'Books'), (2, 'Business'), (3, 'Education'), (4, 'Entertainment'),
 (5, 'Finance'), (6, 'Games'), (7, 'Health & Fitness'), (8, 'Lifestyle'),
 (9, 'Medical'), (10, 'Music'), (11, 'Navigation'), (12, 'News'),
 (13, 'Photo & Video'), (14, 'Productivity'), (15, 'Reference'), (16, 'Social Networking'),
 (17, 'Sports'), (18, 'Travel'), (19, 'Utilities'), (20, 'Weather'),
 (21, 'Widget');


-- -----------------------------------------------------
-- insert country
-- -----------------------------------------------------
INSERT INTO country (iso2, short_name, long_name, iso3, numcode, un_member, calling_code, cctld) VALUES
 ('AD', 'Andorra', 'Principality of Andorra', 'AND', '020', 'yes', '376', '.ad'),
 ('AE', 'United Arab Emirates', 'United Arab Emirates', 'ARE', '784', 'yes', '971', '.ae'),
 ('AF', 'Afghanistan', 'Islamic Republic of Afghanistan', 'AFG', '004', 'yes', '93', '.af'),
 ('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'ATG', '028', 'yes', '1+268', '.ag'),
 ('AI', 'Anguilla', 'Anguilla', 'AIA', '660', 'no', '1+264', '.ai'),
 ('AL', 'Albania', 'Republic of Albania', 'ALB', '008', 'yes', '355', '.al'),
 ('AM', 'Armenia', 'Republic of Armenia', 'ARM', '051', 'yes', '374', '.am'),
 ('AO', 'Angola', 'Republic of Angola', 'AGO', '024', 'yes', '244', '.ao'),
 ('AQ', 'Antarctica', 'Antarctica', 'ATA', '010', 'no', '672', '.aq'),
 ('AR', 'Argentina', 'Argentine Republic', 'ARG', '032', 'yes', '54', '.ar'),
 ('AS', 'American Samoa', 'American Samoa', 'ASM', '016', 'no', '1+684', '.as'),
 ('AT', 'Austria', 'Republic of Austria', 'AUT', '040', 'yes', '43', '.at'),
 ('AU', 'Australia', 'Commonwealth of Australia', 'AUS', '036', 'yes', '61', '.au'),
 ('AW', 'Aruba', 'Aruba', 'ABW', '533', 'no', '297', '.aw'),
 ('AX', 'Aland Islands', '&Aring;land Islands', 'ALA', '248', 'no', '358', '.ax'),
 ('AZ', 'Azerbaijan', 'Republic of Azerbaijan', 'AZE', '031', 'yes', '994', '.az'),
 ('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', '070', 'yes', '387', '.ba'),
 ('BB', 'Barbados', 'Barbados', 'BRB', '052', 'yes', '1+246', '.bb'),
 ('BD', 'Bangladesh', 'People\'s Republic of Bangladesh', 'BGD', '050', 'yes', '880', '.bd'),
 ('BE', 'Belgium', 'Kingdom of Belgium', 'BEL', '056', 'yes', '32', '.be'),
 ('BF', 'Burkina Faso', 'Burkina Faso', 'BFA', '854', 'yes', '226', '.bf'),
 ('BG', 'Bulgaria', 'Republic of Bulgaria', 'BGR', '100', 'yes', '359', '.bg'),
 ('BH', 'Bahrain', 'Kingdom of Bahrain', 'BHR', '048', 'yes', '973', '.bh'),
 ('BI', 'Burundi', 'Republic of Burundi', 'BDI', '108', 'yes', '257', '.bi'),
 ('BJ', 'Benin', 'Republic of Benin', 'BEN', '204', 'yes', '229', '.bj'),
 ('BL', 'Saint Barthelemy', 'Saint Barth&eacute;lemy', 'BLM', '652', 'no', '590', '.bl'),
 ('BM', 'Bermuda', 'Bermuda Islands', 'BMU', '060', 'no', '1+441', '.bm'),
 ('BN', 'Brunei', 'Brunei Darussalam', 'BRN', '096', 'yes', '673', '.bn'),
 ('BO', 'Bolivia', 'Plurinational State of Bolivia', 'BOL', '068', 'yes', '591', '.bo'),
 ('BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'BES', '535', 'no', '599', '.bq'),
 ('BR', 'Brazil', 'Federative Republic of Brazil', 'BRA', '076', 'yes', '55', '.br'),
 ('BS', 'Bahamas', 'Commonwealth of The Bahamas', 'BHS', '044', 'yes', '1+242', '.bs'),
 ('BT', 'Bhutan', 'Kingdom of Bhutan', 'BTN', '064', 'yes', '975', '.bt'),
 ('BV', 'Bouvet Island', 'Bouvet Island', 'BVT', '074', 'no', 'NONE', '.bv'),
 ('BW', 'Botswana', 'Republic of Botswana', 'BWA', '072', 'yes', '267', '.bw'),
 ('BY', 'Belarus', 'Republic of Belarus', 'BLR', '112', 'yes', '375', '.by'),
 ('BZ', 'Belize', 'Belize', 'BLZ', '084', 'yes', '501', '.bz'),
 ('CA', 'Canada', 'Canada', 'CAN', '124', 'yes', '1', '.ca'),
 ('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CCK', '166', 'no', '61', '.cc'),
 ('CD', 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'COD', '180', 'yes', '243', '.cd'),
 ('CF', 'Central African Republic', 'Central African Republic', 'CAF', '140', 'yes', '236', '.cf'),
 ('CG', 'Congo', 'Republic of the Congo', 'COG', '178', 'yes', '242', '.cg'),
 ('CH', 'Switzerland', 'Swiss Confederation', 'CHE', '756', 'yes', '41', '.ch'),
 ('CI', 'Cote d\'ivoire (Ivory Coast)', 'Republic of C&ocirc;te D\'Ivoire (Ivory Coast)', 'CIV', '384', 'yes', '225', '.ci'),
 ('CK', 'Cook Islands', 'Cook Islands', 'COK', '184', 'some', '682', '.ck'),
 ('CL', 'Chile', 'Republic of Chile', 'CHL', '152', 'yes', '56', '.cl'),
 ('CM', 'Cameroon', 'Republic of Cameroon', 'CMR', '120', 'yes', '237', '.cm'),
 ('CN', 'China', 'People\'s Republic of China', 'CHN', '156', 'yes', '86', '.cn'),
 ('CO', 'Colombia', 'Republic of Colombia', 'COL', '170', 'yes', '57', '.co'),
 ('CR', 'Costa Rica', 'Republic of Costa Rica', 'CRI', '188', 'yes', '506', '.cr'),
 ('CU', 'Cuba', 'Republic of Cuba', 'CUB', '192', 'yes', '53', '.cu'),
 ('CV', 'Cape Verde', 'Republic of Cape Verde', 'CPV', '132', 'yes', '238', '.cv'),
 ('CW', 'Curacao', 'Cura&ccedil;ao', 'CUW', '531', 'no', '599', '.cw'),
 ('CX', 'Christmas Island', 'Christmas Island', 'CXR', '162', 'no', '61', '.cx'),
 ('CY', 'Cyprus', 'Republic of Cyprus', 'CYP', '196', 'yes', '357', '.cy'),
 ('CZ', 'Czech Republic', 'Czech Republic', 'CZE', '203', 'yes', '420', '.cz'),
 ('DE', 'Germany', 'Federal Republic of Germany', 'DEU', '276', 'yes', '49', '.de'),
 ('DJ', 'Djibouti', 'Republic of Djibouti', 'DJI', '262', 'yes', '253', '.dj'),
 ('DK', 'Denmark', 'Kingdom of Denmark', 'DNK', '208', 'yes', '45', '.dk'),
 ('DM', 'Dominica', 'Commonwealth of Dominica', 'DMA', '212', 'yes', '1+767', '.dm'),
 ('DO', 'Dominican Republic', 'Dominican Republic', 'DOM', '214', 'yes', '1+809, 8', '.do'),
 ('DZ', 'Algeria', 'People\'s Democratic Republic of Algeria', 'DZA', '012', 'yes', '213', '.dz'),
 ('EC', 'Ecuador', 'Republic of Ecuador', 'ECU', '218', 'yes', '593', '.ec'),
 ('EE', 'Estonia', 'Republic of Estonia', 'EST', '233', 'yes', '372', '.ee'),
 ('EG', 'Egypt', 'Arab Republic of Egypt', 'EGY', '818', 'yes', '20', '.eg'),
 ('EH', 'Western Sahara', 'Western Sahara', 'ESH', '732', 'no', '212', '.eh'),
 ('ER', 'Eritrea', 'State of Eritrea', 'ERI', '232', 'yes', '291', '.er'),
 ('ES', 'Spain', 'Kingdom of Spain', 'ESP', '724', 'yes', '34', '.es'),
 ('ET', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ETH', '231', 'yes', '251', '.et'),
 ('FI', 'Finland', 'Republic of Finland', 'FIN', '246', 'yes', '358', '.fi'),
 ('FJ', 'Fiji', 'Republic of Fiji', 'FJI', '242', 'yes', '679', '.fj'),
 ('FK', 'Falkland Islands (Malvinas)', 'The Falkland Islands (Malvinas)', 'FLK', '238', 'no', '500', '.fk'),
 ('FM', 'Micronesia', 'Federated States of Micronesia', 'FSM', '583', 'yes', '691', '.fm'),
 ('FO', 'Faroe Islands', 'The Faroe Islands', 'FRO', '234', 'no', '298', '.fo'),
 ('FR', 'France', 'French Republic', 'FRA', '250', 'yes', '33', '.fr'),
 ('GA', 'Gabon', 'Gabonese Republic', 'GAB', '266', 'yes', '241', '.ga'),
 ('GB', 'United Kingdom', 'United Kingdom of Great Britain and Nothern Ireland', 'GBR', '826', 'yes', '44', '.uk'),
 ('GD', 'Grenada', 'Grenada', 'GRD', '308', 'yes', '1+473', '.gd'),
 ('GE', 'Georgia', 'Georgia', 'GEO', '268', 'yes', '995', '.ge'),
 ('GF', 'French Guiana', 'French Guiana', 'GUF', '254', 'no', '594', '.gf'),
 ('GG', 'Guernsey', 'Guernsey', 'GGY', '831', 'no', '44', '.gg'),
 ('GH', 'Ghana', 'Republic of Ghana', 'GHA', '288', 'yes', '233', '.gh'),
 ('GI', 'Gibraltar', 'Gibraltar', 'GIB', '292', 'no', '350', '.gi'),
 ('GL', 'Greenland', 'Greenland', 'GRL', '304', 'no', '299', '.gl'),
 ('GM', 'Gambia', 'Republic of The Gambia', 'GMB', '270', 'yes', '220', '.gm'),
 ('GN', 'Guinea', 'Republic of Guinea', 'GIN', '324', 'yes', '224', '.gn'),
 ('GP', 'Guadaloupe', 'Guadeloupe', 'GLP', '312', 'no', '590', '.gp'),
 ('GQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'GNQ', '226', 'yes', '240', '.gq'),
 ('GR', 'Greece', 'Hellenic Republic', 'GRC', '300', 'yes', '30', '.gr'),
 ('GS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'SGS', '239', 'no', '500', '.gs'),
 ('GT', 'Guatemala', 'Republic of Guatemala', 'GTM', '320', 'yes', '502', '.gt'),
 ('GU', 'Guam', 'Guam', 'GUM', '316', 'no', '1+671', '.gu'),
 ('GW', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'GNB', '624', 'yes', '245', '.gw'),
 ('GY', 'Guyana', 'Co-operative Republic of Guyana', 'GUY', '328', 'yes', '592', '.gy'),
 ('HK', 'Hong Kong', 'Hong Kong', 'HKG', '344', 'no', '852', '.hk'),
 ('HM', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HMD', '334', 'no', 'NONE', '.hm'),
 ('HN', 'Honduras', 'Republic of Honduras', 'HND', '340', 'yes', '504', '.hn'),
 ('HR', 'Croatia', 'Republic of Croatia', 'HRV', '191', 'yes', '385', '.hr'),
 ('HT', 'Haiti', 'Republic of Haiti', 'HTI', '332', 'yes', '509', '.ht'),
 ('HU', 'Hungary', 'Hungary', 'HUN', '348', 'yes', '36', '.hu'),
 ('ID', 'Indonesia', 'Republic of Indonesia', 'IDN', '360', 'yes', '62', '.id'),
 ('IE', 'Ireland', 'Ireland', 'IRL', '372', 'yes', '353', '.ie'),
 ('IL', 'Israel', 'State of Israel', 'ISR', '376', 'yes', '972', '.il'),
 ('IM', 'Isle of Man', 'Isle of Man', 'IMN', '833', 'no', '44', '.im'),
 ('IN', 'India', 'Republic of India', 'IND', '356', 'yes', '91', '.in'),
 ('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'IOT', '086', 'no', '246', '.io'),
 ('IQ', 'Iraq', 'Republic of Iraq', 'IRQ', '368', 'yes', '964', '.iq'),
 ('IR', 'Iran', 'Islamic Republic of Iran', 'IRN', '364', 'yes', '98', '.ir'),
 ('IS', 'Iceland', 'Republic of Iceland', 'ISL', '352', 'yes', '354', '.is'),
 ('IT', 'Italy', 'Italian Republic', 'ITA', '380', 'yes', '39', '.jm'),
 ('JE', 'Jersey', 'The Bailiwick of Jersey', 'JEY', '832', 'no', '44', '.je'),
 ('JM', 'Jamaica', 'Jamaica', 'JAM', '388', 'yes', '1+876', '.jm'),
 ('JO', 'Jordan', 'Hashemite Kingdom of Jordan', 'JOR', '400', 'yes', '962', '.jo'),
 ('JP', 'Japan', 'Japan', 'JPN', '392', 'yes', '81', '.jp'),
 ('KE', 'Kenya', 'Republic of Kenya', 'KEN', '404', 'yes', '254', '.ke'),
 ('KG', 'Kyrgyzstan', 'Kyrgyz Republic', 'KGZ', '417', 'yes', '996', '.kg'),
 ('KH', 'Cambodia', 'Kingdom of Cambodia', 'KHM', '116', 'yes', '855', '.kh'),
 ('KI', 'Kiribati', 'Republic of Kiribati', 'KIR', '296', 'yes', '686', '.ki'),
 ('KM', 'Comoros', 'Union of the Comoros', 'COM', '174', 'yes', '269', '.km'),
 ('KN', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'KNA', '659', 'yes', '1+869', '.kn'),
 ('KP', 'North Korea', 'Democratic People\'s Republic of Korea', 'PRK', '408', 'yes', '850', '.kp'),
 ('KR', 'South Korea', 'Republic of Korea', 'KOR', '410', 'yes', '82', '.kr'),
 ('KW', 'Kuwait', 'State of Kuwait', 'KWT', '414', 'yes', '965', '.kw'),
 ('KY', 'Cayman Islands', 'The Cayman Islands', 'CYM', '136', 'no', '1+345', '.ky'),
 ('KZ', 'Kazakhstan', 'Republic of Kazakhstan', 'KAZ', '398', 'yes', '7', '.kz'),
 ('LA', 'Laos', 'Lao People\'s Democratic Republic', 'LAO', '418', 'yes', '856', '.la'),
 ('LB', 'Lebanon', 'Republic of Lebanon', 'LBN', '422', 'yes', '961', '.lb'),
 ('LC', 'Saint Lucia', 'Saint Lucia', 'LCA', '662', 'yes', '1+758', '.lc'),
 ('LI', 'Liechtenstein', 'Principality of Liechtenstein', 'LIE', '438', 'yes', '423', '.li'),
 ('LK', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LKA', '144', 'yes', '94', '.lk'),
 ('LR', 'Liberia', 'Republic of Liberia', 'LBR', '430', 'yes', '231', '.lr'),
 ('LS', 'Lesotho', 'Kingdom of Lesotho', 'LSO', '426', 'yes', '266', '.ls'),
 ('LT', 'Lithuania', 'Republic of Lithuania', 'LTU', '440', 'yes', '370', '.lt'),
 ('LU', 'Luxembourg', 'Grand Duchy of Luxembourg', 'LUX', '442', 'yes', '352', '.lu'),
 ('LV', 'Latvia', 'Republic of Latvia', 'LVA', '428', 'yes', '371', '.lv'),
 ('LY', 'Libya', 'Libya', 'LBY', '434', 'yes', '218', '.ly'),
 ('MA', 'Morocco', 'Kingdom of Morocco', 'MAR', '504', 'yes', '212', '.ma'),
 ('MC', 'Monaco', 'Principality of Monaco', 'MCO', '492', 'yes', '377', '.mc'),
 ('MD', 'Moldava', 'Republic of Moldova', 'MDA', '498', 'yes', '373', '.md'),
 ('ME', 'Montenegro', 'Montenegro', 'MNE', '499', 'yes', '382', '.me'),
 ('MF', 'Saint Martin', 'Saint Martin', 'MAF', '663', 'no', '590', '.mf'),
 ('MG', 'Madagascar', 'Republic of Madagascar', 'MDG', '450', 'yes', '261', '.mg'),
 ('MH', 'Marshall Islands', 'Republic of the Marshall Islands', 'MHL', '584', 'yes', '692', '.mh'),
 ('MK', 'Macedonia', 'The Former Yugoslav Republic of Macedonia', 'MKD', '807', 'yes', '389', '.mk'),
 ('ML', 'Mali', 'Republic of Mali', 'MLI', '466', 'yes', '223', '.ml'),
 ('MM', 'Myanmar (Burma)', 'Republic of the Union of Myanmar', 'MMR', '104', 'yes', '95', '.mm'),
 ('MN', 'Mongolia', 'Mongolia', 'MNG', '496', 'yes', '976', '.mn'),
 ('MO', 'Macao', 'The Macao Special Administrative Region', 'MAC', '446', 'no', '853', '.mo'),
 ('MP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'MNP', '580', 'no', '1+670', '.mp'),
 ('MQ', 'Martinique', 'Martinique', 'MTQ', '474', 'no', '596', '.mq'),
 ('MR', 'Mauritania', 'Islamic Republic of Mauritania', 'MRT', '478', 'yes', '222', '.mr'),
 ('MS', 'Montserrat', 'Montserrat', 'MSR', '500', 'no', '1+664', '.ms'),
 ('MT', 'Malta', 'Republic of Malta', 'MLT', '470', 'yes', '356', '.mt'),
 ('MU', 'Mauritius', 'Republic of Mauritius', 'MUS', '480', 'yes', '230', '.mu'),
 ('MV', 'Maldives', 'Republic of Maldives', 'MDV', '462', 'yes', '960', '.mv'),
 ('MW', 'Malawi', 'Republic of Malawi', 'MWI', '454', 'yes', '265', '.mw'),
 ('MX', 'Mexico', 'United Mexican States', 'MEX', '484', 'yes', '52', '.mx'),
 ('MY', 'Malaysia', 'Malaysia', 'MYS', '458', 'yes', '60', '.my'),
 ('MZ', 'Mozambique', 'Republic of Mozambique', 'MOZ', '508', 'yes', '258', '.mz'),
 ('NA', 'Namibia', 'Republic of Namibia', 'NAM', '516', 'yes', '264', '.na'),
 ('NC', 'New Caledonia', 'New Caledonia', 'NCL', '540', 'no', '687', '.nc'),
 ('NE', 'Niger', 'Republic of Niger', 'NER', '562', 'yes', '227', '.ne'),
 ('NF', 'Norfolk Island', 'Norfolk Island', 'NFK', '574', 'no', '672', '.nf'),
 ('NG', 'Nigeria', 'Federal Republic of Nigeria', 'NGA', '566', 'yes', '234', '.ng'),
 ('NI', 'Nicaragua', 'Republic of Nicaragua', 'NIC', '558', 'yes', '505', '.ni'),
 ('NL', 'Netherlands', 'Kingdom of the Netherlands', 'NLD', '528', 'yes', '31', '.nl'),
 ('NO', 'Norway', 'Kingdom of Norway', 'NOR', '578', 'yes', '47', '.no'),
 ('NP', 'Nepal', 'Federal Democratic Republic of Nepal', 'NPL', '524', 'yes', '977', '.np'),
 ('NR', 'Nauru', 'Republic of Nauru', 'NRU', '520', 'yes', '674', '.nr'),
 ('NU', 'Niue', 'Niue', 'NIU', '570', 'some', '683', '.nu'),
 ('NZ', 'New Zealand', 'New Zealand', 'NZL', '554', 'yes', '64', '.nz'),
 ('OM', 'Oman', 'Sultanate of Oman', 'OMN', '512', 'yes', '968', '.om'),
 ('PA', 'Panama', 'Republic of Panama', 'PAN', '591', 'yes', '507', '.pa'),
 ('PE', 'Peru', 'Republic of Peru', 'PER', '604', 'yes', '51', '.pe'),
 ('PF', 'French Polynesia', 'French Polynesia', 'PYF', '258', 'no', '689', '.pf'),
 ('PG', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'PNG', '598', 'yes', '675', '.pg'),
 ('PH', 'Phillipines', 'Republic of the Philippines', 'PHL', '608', 'yes', '63', '.ph'),
 ('PK', 'Pakistan', 'Islamic Republic of Pakistan', 'PAK', '586', 'yes', '92', '.pk'),
 ('PL', 'Poland', 'Republic of Poland', 'POL', '616', 'yes', '48', '.pl'),
 ('PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'SPM', '666', 'no', '508', '.pm'),
 ('PN', 'Pitcairn', 'Pitcairn', 'PCN', '612', 'no', 'NONE', '.pn'),
 ('PR', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'PRI', '630', 'no', '1+939', '.pr'),
 ('PS', 'Palestine', 'State of Palestine (or Occupied Palestinian Territory)', 'PSE', '275', 'some', '970', '.ps'),
 ('PT', 'Portugal', 'Portuguese Republic', 'PRT', '620', 'yes', '351', '.pt'),
 ('PW', 'Palau', 'Republic of Palau', 'PLW', '585', 'yes', '680', '.pw'),
 ('PY', 'Paraguay', 'Republic of Paraguay', 'PRY', '600', 'yes', '595', '.py'),
 ('QA', 'Qatar', 'State of Qatar', 'QAT', '634', 'yes', '974', '.qa'),
 ('RE', 'Reunion', 'R&eacute;union', 'REU', '638', 'no', '262', '.re'),
 ('RO', 'Romania', 'Romania', 'ROU', '642', 'yes', '40', '.ro'),
 ('RS', 'Serbia', 'Republic of Serbia', 'SRB', '688', 'yes', '381', '.rs'),
 ('RU', 'Russia', 'Russian Federation', 'RUS', '643', 'yes', '7', '.ru'),
 ('RW', 'Rwanda', 'Republic of Rwanda', 'RWA', '646', 'yes', '250', '.rw'),
 ('SA', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'SAU', '682', 'yes', '966', '.sa'),
 ('SB', 'Solomon Islands', 'Solomon Islands', 'SLB', '090', 'yes', '677', '.sb'),
 ('SC', 'Seychelles', 'Republic of Seychelles', 'SYC', '690', 'yes', '248', '.sc'),
 ('SD', 'Sudan', 'Republic of the Sudan', 'SDN', '729', 'yes', '249', '.sd'),
 ('SE', 'Sweden', 'Kingdom of Sweden', 'SWE', '752', 'yes', '46', '.se'),
 ('SG', 'Singapore', 'Republic of Singapore', 'SGP', '702', 'yes', '65', '.sg'),
 ('SH', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '654', 'no', '290', '.sh'),
 ('SI', 'Slovenia', 'Republic of Slovenia', 'SVN', '705', 'yes', '386', '.si'),
 ('SJ', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'SJM', '744', 'no', '47', '.sj'),
 ('SK', 'Slovakia', 'Slovak Republic', 'SVK', '703', 'yes', '421', '.sk'),
 ('SL', 'Sierra Leone', 'Republic of Sierra Leone', 'SLE', '694', 'yes', '232', '.sl'),
 ('SM', 'San Marino', 'Republic of San Marino', 'SMR', '674', 'yes', '378', '.sm'),
 ('SN', 'Senegal', 'Republic of Senegal', 'SEN', '686', 'yes', '221', '.sn'),
 ('SO', 'Somalia', 'Somali Republic', 'SOM', '706', 'yes', '252', '.so'),
 ('SR', 'Suriname', 'Republic of Suriname', 'SUR', '740', 'yes', '597', '.sr'),
 ('SS', 'South Sudan', 'Republic of South Sudan', 'SSD', '728', 'yes', '211', '.ss'),
 ('ST', 'Sao Tome and Principe', 'Democratic Republic of S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'STP', '678', 'yes', '239', '.st'),
 ('SV', 'El Salvador', 'Republic of El Salvador', 'SLV', '222', 'yes', '503', '.sv'),
 ('SX', 'Sint Maarten', 'Sint Maarten', 'SXM', '534', 'no', '1+721', '.sx'),
 ('SY', 'Syria', 'Syrian Arab Republic', 'SYR', '760', 'yes', '963', '.sy'),
 ('SZ', 'Swaziland', 'Kingdom of Swaziland', 'SWZ', '748', 'yes', '268', '.sz'),
 ('TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'TCA', '796', 'no', '1+649', '.tc'),
 ('TD', 'Chad', 'Republic of Chad', 'TCD', '148', 'yes', '235', '.td'),
 ('TF', 'French Southern Territories', 'French Southern Territories', 'ATF', '260', 'no', '', '.tf'),
 ('TG', 'Togo', 'Togolese Republic', 'TGO', '768', 'yes', '228', '.tg'),
 ('TH', 'Thailand', 'Kingdom of Thailand', 'THA', '764', 'yes', '66', '.th'),
 ('TJ', 'Tajikistan', 'Republic of Tajikistan', 'TJK', '762', 'yes', '992', '.tj'),
 ('TK', 'Tokelau', 'Tokelau', 'TKL', '772', 'no', '690', '.tk'),
 ('TL', 'Timor-Leste (East Timor)', 'Democratic Republic of Timor-Leste', 'TLS', '626', 'yes', '670', '.tl'),
 ('TM', 'Turkmenistan', 'Turkmenistan', 'TKM', '795', 'yes', '993', '.tm'),
 ('TN', 'Tunisia', 'Republic of Tunisia', 'TUN', '788', 'yes', '216', '.tn'),
 ('TO', 'Tonga', 'Kingdom of Tonga', 'TON', '776', 'yes', '676', '.to'),
 ('TR', 'Turkey', 'Republic of Turkey', 'TUR', '792', 'yes', '90', '.tr'),
 ('TT', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TTO', '780', 'yes', '1+868', '.tt'),
 ('TV', 'Tuvalu', 'Tuvalu', 'TUV', '798', 'yes', '688', '.tv'),
 ('TW', 'Taiwan', 'Republic of China (Taiwan)', 'TWN', '158', 'former', '886', '.tw'),
 ('TZ', 'Tanzania', 'United Republic of Tanzania', 'TZA', '834', 'yes', '255', '.tz'),
 ('UA', 'Ukraine', 'Ukraine', 'UKR', '804', 'yes', '380', '.ua'),
 ('UG', 'Uganda', 'Republic of Uganda', 'UGA', '800', 'yes', '256', '.ug'),
 ('UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UMI', '581', 'no', 'NONE', 'NONE'),
 ('US', 'United States', 'United States of America', 'USA', '840', 'yes', '1', '.us'),
 ('UY', 'Uruguay', 'Eastern Republic of Uruguay', 'URY', '858', 'yes', '598', '.uy'),
 ('UZ', 'Uzbekistan', 'Republic of Uzbekistan', 'UZB', '860', 'yes', '998', '.uz'),
 ('VA', 'Vatican City', 'State of the Vatican City', 'VAT', '336', 'no', '39', '.va'),
 ('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VCT', '670', 'yes', '1+784', '.vc'),
 ('VE', 'Venezuela', 'Bolivarian Republic of Venezuela', 'VEN', '862', 'yes', '58', '.ve'),
 ('VG', 'Virgin Islands, British', 'British Virgin Islands', 'VGB', '092', 'no', '1+284', '.vg'),
 ('VI', 'Virgin Islands, US', 'Virgin Islands of the United States', 'VIR', '850', 'no', '1+340', '.vi'),
 ('VN', 'Vietnam', 'Socialist Republic of Vietnam', 'VNM', '704', 'yes', '84', '.vn'),
 ('VU', 'Vanuatu', 'Republic of Vanuatu', 'VUT', '548', 'yes', '678', '.vu'),
 ('WF', 'Wallis and Futuna', 'Wallis and Futuna', 'WLF', '876', 'no', '681', '.wf'),
 ('WS', 'Samoa', 'Independent State of Samoa', 'WSM', '882', 'yes', '685', '.ws'),
 ('XK', 'Kosovo', 'Republic of Kosovo', '---', '---', 'some', '381', ''),
 ('YE', 'Yemen', 'Republic of Yemen', 'YEM', '887', 'yes', '967', '.ye'),
 ('YT', 'Mayotte', 'Mayotte', 'MYT', '175', 'no', '262', '.yt'),
 ('ZA', 'South Africa', 'Republic of South Africa', 'ZAF', '710', 'yes', '27', '.za'),
 ('ZM', 'Zambia', 'Republic of Zambia', 'ZMB', '894', 'yes', '260', '.zm'),
 ('ZW', 'Zimbabwe', 'Republic of Zimbabwe', 'ZWE', '716', 'yes', '263', '.zw');


-- -----------------------------------------------------
-- insert sequence
-- -----------------------------------------------------
INSERT INTO sequence (name, currval) VALUES
 ('seq_appkey', '0'),
 ('seq_componentkey', '0');

